before_script:
    - date
    - uname -a
    - printenv | sort

gcc:
    image: gpdowning/gcc
    script:
    - ls -al
    - cd cpp
    - ls -al
    - cat Makefile
    - make versions
    - ls -al
    - make run
    - ls -al
